function restoreOptions() {
  chrome.storage.local.get(null, function(items) {
    var settings = items || {};
    
    $("#background_color").prop("value", settings["background_color"] || "#cccccc");
    $("#custom_icon_data").prop("value", settings["custom_icon_data"] || "{}");
    $("#center_vertically").prop("checked", String(settings["center_vertically"]) === "true");
    $("#folder_list").prop("value", settings["default_folder_id"] || "1");
    $("#dial_columns").prop("value", settings["dial_columns"] || "6");
    $("#dial_width").prop("value", settings["dial_width"] || "70");
    $("#drag_and_drop").prop("checked", String(settings["drag_and_drop"]) === "true");
    $("#enable_sync").prop("checked", String(settings["enable_sync"]) === "true");
    $("#folder_color").prop("value", settings["folder_color"] || "#888888");
    $("#show_advanced").prop("checked", String(settings["show_advanced"]) === "true");
    $("#show_folder_list").prop("checked", String(settings["show_folder_list"]) === "true");
    $("#show_new_entry").prop("checked", String(settings["show_new_entry"]) === "true");
    $("#show_options_gear").prop("checked", String(settings["show_options_gear"]) === "true");
    $("#show_subfolder_icons").prop("checked", String(settings["show_subfolder_icons"]) === "true");

    if (String(settings["show_advanced"]) === "false") {
      $("#advanced").hide();
    } else {
      $("#advanced").show();
    }
  });
}

function saveOptions() {
  var updatedSettings = {
    "background_color": $("#background_color").prop("value"),
    "custom_icon_data": JSON.stringify(JSON.parse($("#custom_icon_data").prop("value"))),
    "center_vertically": String($("#center_vertically").prop("checked")),
    "default_folder_id": $("#folder_list").prop("value"),
    "dial_columns": $("#dial_columns").prop("value"),
    "dial_width": $("#dial_width").prop("value"),
    "drag_and_drop": String($("#drag_and_drop").prop("checked")),
    "enable_sync": String($("#enable_sync").prop("checked")),
    "folder_color": $("#folder_color").prop("value"),
    "show_advanced": String($("#show_advanced").prop("checked")),
    "show_folder_list": String($("#show_folder_list").prop("checked")),
    "show_new_entry": String($("#show_new_entry").prop("checked")),
    "show_options_gear": String($("#show_options_gear").prop("checked")),
    "show_subfolder_icons": String($("#show_subfolder_icons").prop("checked"))
  };

  chrome.storage.local.set(updatedSettings, function() {
    if (updatedSettings["enable_sync"] === "true") {
      if (typeof syncToStorage === "function") {
        syncToStorage();
      }
    }
    // Instantly closes the options tab and drops to native clean tab
    chrome.tabs.getCurrent(function(tab) {
      chrome.tabs.update(tab.id, { url: "chrome://newtab/" });
    });
  });
}

document.addEventListener("DOMContentLoaded", function() {
  ensureDefaultsAndInit(function() {
    
    // 1. Set up an observer to watch when the folder dropdown is dynamically added
    var targetNode = document.getElementById('folder');
    if (targetNode) {
      var observer = new MutationObserver(function(mutations, obs) {
        // Look for the select element generated by initialize()
        if (document.getElementById('folder_list')) {
          restoreOptions(); // Hydrate the form fields now that the element exists!
          obs.disconnect(); // Stop observing since our job is done
        }
      });
      
      // Start monitoring the folder div for changes
      observer.observe(targetNode, { childList: true, subtree: true });
    }

    // 2. Run your original initialize function as a black box
    initialize();
  });

  $("#save").on("click", function() {
    try { 
      JSON.parse($("#custom_icon_data").prop("value"));
      saveOptions();
    } catch (e) {
      alert("The JSON you entered is not valid, try again.\nThe error message was: " + e);
    }
  });

  $("#cancel").on("click", function() {
    chrome.tabs.getCurrent(function(tab) {
      chrome.tabs.update(tab.id, { url: "chrome://newtab/" });
    });
  });

  $(document.body).on("keyup", function(e) {
    if (e.which === 27) { 
      chrome.tabs.getCurrent(function(tab) {
        chrome.tabs.update(tab.id, { url: "chrome://newtab/" });
      });
    }
  });

  $("#background_color").on("change", function() {
    document.body.style.backgroundColor = $("#background_color").prop("value");
  });

  $("#enable_sync").on("click", function() {
    if (this.checked) {
      chrome.storage.sync.getBytesInUse(null, function (bytes) {
        if (bytes > 0) {
          if (confirm("You have previously synchronized data!!\n"+
          "Do you want to overwrite your current local settings with your previously saved remote settings?")) {
            if (typeof restoreFromSync === "function") {
              restoreFromSync();
            }
          }
        }
      });
    }
  });

  $("#show_advanced").on("click", function() {
    if (this.checked) {
      $("#advanced").show();
    } else {
      $("#advanced").hide();
    }
  });

  $("#custom_icon_data").on("keydown", function (e) {
    if (e.which === 13) { 
      $("#save").trigger("click");
    }
  });

  $("#reset_local_settings").on("click", function() {
    if (confirm("Are you sure you want to reset all local values you have changed back to their defaults?")) {
      chrome.storage.local.clear(function() {
        ensureDefaultsAndInit(function() {
          window.location.reload();
        });
      });
    }
  });

  $("#reset_synced_settings").on("click", function() {
    if (confirm("Are you sure you want to delete all previously synchronized data to start fresh?")) {
      chrome.storage.sync.clear();
    }
  });
});